version: '3.9'

services:
  db:
    image: postgres:13.2
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  api:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./server/assets:/app/assets:rw
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
  front:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "5173:5173"
    depends_on:
      - api
  relay:
    build:
      context: relay
      dockerfile: Dockerfile
    container_name: relay
    ports:
      - "9001:9001"
