version: '3.9'

services:
  db:
    image: postgres:13.2
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  api:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./server/assets:/app/src/assets:rw
    ports:
      - "3000:3000"
  front:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "5173:5173"
    depends_on:
      - api