version: '3.9'

services:
  db:
    image: postgres:13.2
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  web:
    build: .
    container_name: web
    volumes:
      - ./src/assets:/app/src/assets